included:
- XcodeGenTestApp
- XcodeGenTestAppTests
- XcodeGenTestAppUITests
- Petstore
- PetstoreTests

excluded:
- Carthage
- XcodeGenTestApp/Generated

disabled_rules:
- line_length
- trailing_whitespace

identifier_name:
  min_length: 2
  allowed_symbols: "_"